################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  http:
    address: :80
  https:
    address: :443

################################################################
# Traefik logs configuration
################################################################
log:
  level: INFO

accessLog: {}

################################################################
# API and dashboard configuration
################################################################
api:
  insecure: true
  dashboard: true

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    defaultRule: Host(`{{ .Name|replace "-" "."}}.localhost`)
    exposedByDefault: false
    network: techcare