version: "3.9"

services:
  app1:
    image: nginx:1.19-alpine
    restart: unless-stopped
    labels:
      traefik.docker.network: "techcare"
      traefik.enable: true
    networks:
      techcare:
        aliases:
          - web_one_techare
    volumes:
      - "$PWD/one/config/default.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/one:/var/www/html"

  app2:
    image: nginx:1.19-alpine
    restart: unless-stopped
    labels:
      traefik.docker.network: "techcare"
      traefik.enable: true
      traefik.http.routers.app2.rule: "Host(`app1.examples.localhost`) && PathPrefix(`/api`)"
    networks:
      techcare:
        aliases:
          - web_two_techare
    volumes:
      - "$PWD/two/config/default.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/two:/var/www/html"
networks:
    techcare:
        external: true